version: '3.8'
services:
  node1:
    image: mysql:8.0
    container_name: node1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games
      MYSQL_ROOT_HOST: '%'
      command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  node2:
    image: mysql:8.0
    container_name: node2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

  node3:
    image: mysql:8.0
    container_name: node3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: games
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"

networks:
  default:
    driver: bridge
